### ISSUE TITLE
Not working on linux/arm64

### ISSUE THREAD

**Issue by ndechesne** [sindresorhus/fast-cli#15]
hi,

i am trying this on an arm64 platform (not x86):

# npm install --global fast-cli
|
> phantomjs-prebuilt@2.1.13 install /usr/local/lib/node_modules/fast-cli/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.23-linaro-lt-qcom
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "fast-cli"
npm ERR! cwd /root
npm ERR! node -v v4.4.3
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

I am running on a small embedded development platform, running Debian Jessie.

**Comment by sindresorhus** [comment]
You need to manually install PhantomJS globally. Not sure whether it's available for ARM. Try `speed-test` instead ;)
