### ISSUE TITLE
Broken on Centos 7

### ISSUE THREAD

**Issue by thetravellor** [sindresorhus/fast-cli#25]
node --version
v10.6.0

 npm install --global fast-cli
/usr/bin/fast -> /usr/lib/node_modules/fast-cli/cli.js

> puppeteer@1.5.0 install /usr/lib/node_modules/fast-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-10T23_18_13_776Z-debug.log
[root@family ~]#

**Comment by sindresorhus** [comment]
This is a problem on your end with permissions and installing. Nothing to do with this module specifically. Use https://npm.community/c/support for npm support.

**Comment by thetravellor** [comment]
Agree that its probably not your module, Its a problem with puppeteer, which you depend on for your module to install and work. Either way, end result is your install is broken as a result. If you don't care, fine - ill log it with google that created it.
