### ISSUE TITLE
Support fast.com's new upload speed test

### ISSUE THREAD

**Issue by GloriousYellow** [sindresorhus/fast-cli#27]

**Comment by sindresorhus** [comment]
👍 But should be behind a `--verbose` flag. Could also include the latency info. PR welcome.

**Comment by GloriousYellow** [comment]
I've started working on it. As the upload speed test does not start after the download test has finished, how should progress reporting be done?

**Comment by GloriousYellow** [comment]
I published a npm module with my changes: `@yellowiki/fast-cli`
