### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by jgroom33** [sindresorhus/fast-cli#31]
Add a Dockerfile to eliminate the npm install requirement

**Comment by sindresorhus** [comment]
No thanks :)

**Comment by jgroom33** [comment]
not fast.com but it's easier than installing npm :)
https://hub.docker.com/r/tianon/speedtest/

or there's this:
https://github.com/jasongwartz/fast-cli/commit/d44e11f30404d0dd38f436957d654a9f6774e9b5
