### ISSUE TITLE
Using stock chromium

### ISSUE THREAD

**Issue by aureooms** [sindresorhus/fast-cli#32]
I have `puppeteer` installed with `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` set and I have `chromium` installed through distribution packages (Arch Linux).
When I try to run `fast`, I get the following:

    $ fast
    Chromium revision is not downloaded. Run "npm install" or "yarn install"

**Comment by sindresorhus** [comment]
You need to also set `PUPPETEER_EXECUTABLE_PATH` so Puppeteer knows where to find the custom Chromium download.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables
