### ISSUE TITLE
ZSH: Command Not Found

### ISSUE THREAD

**Issue by menjilx** [sindresorhus/fast-cli#33]
Hi,

I try to install & run but I got this error.
![image](https://user-images.githubusercontent.com/14908836/53862739-3c3a5680-4023-11e9-8d27-85b3fe358701.png)

Thanks

**Comment by sindresorhus** [comment]
Look at the install output. There might be an error or something. Or you don't have the binary location correctly added in your `$PATH`. Install issues is not really related to this module specifically, but rather npm and your system.

https://docs.npmjs.com/downloading-and-installing-packages-globally
