### ISSUE TITLE
Add ability to run tests using custom settings

### ISSUE THREAD

**Issue by aassaly** [sindresorhus/fast-cli#34]
Fast.com has settings which can be configured and saved on a per-browser basis. Here's a screenshot of the settings:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1593437/55742182-12e36080-59fd-11e9-9123-296e0e6fdefe.png">

Is it possible to add a feature which would enable users to specify the values of these settings from the command line?

**Comment by sindresorhus** [comment]
Possible, yes, but I prefer to keep it simple. Probably better to fork this project. I don’t really want to maintain lots of advanced options.
