### ISSUE TITLE
Failed to launch chrome! Error while loading shared libraries.

### ISSUE THREAD

**Issue by Kashalls** [sindresorhus/fast-cli#35]
Recently installed `fast-cli` globally using `npm isntall -g fast-cli`.

NPM installed `fast-cli` perfectly and all is good until you run the command `fast -u` or just `fast`.

Node Version: v12.2.0
NPM Version: v6.9.0

Screenshot of Console -> https://awau.moe/Pig8hYq.png

**Comment by Kashalls** [comment]
To solve this issue on my end, you need to run `sudo apt install libxss1`. Seems it is not installed on setup/install.

**Comment by sindresorhus** [comment]
The error message already provide you with a troubleshooting link. This has nothing to do with `fast-cli`, but rather Puppeteer.
