### ISSUE TITLE
Raspbian system won't launch Chromium

### ISSUE THREAD

**Issue by xescure** [sindresorhus/fast-cli#37]
I am getting this error for the command `fast`:

```
Failed to launch chrome!
/home/user/.nvm/versions/node/v10.16.1/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: 1: /home/user/.nvm/versions/node/v10.16.1/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

I went through the steps on the troubleshooting link and found that all dependencies are installed except for one. (libappindicator1). However after installing the package, the issue still persists.

**Comment by sindresorhus** [comment]
The error is coming from https://github.com/GoogleChrome/puppeteer and should be opened there instead.

**Comment by K3UL** [comment]
@sindresorhus The solution for this is to use `executablePath` in Puppeteer, to point it to an ARM version of Chromium. Would you consider exposing this parameter in fast-cli ?

**Comment by metropt** [comment]
Face the same problem today. It was nice if it is possible to pass a path as argument

**Comment by paulinechi** [comment]
> Face the same problem today. It would be nice if it is possible to pass a path as argument

Hi I'm facing the same issue today, how did you fixed the problem?

**Comment by mschirrmeister** [comment]
You could set `PUPPETEER_EXECUTABLE_PATH` and point it to your chromium binary. In my Dockerfile I set for example 2 variables.

```
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
```
