### ISSUE TITLE
Fast —download and fast —upload working?

### ISSUE THREAD

**Issue by mpgmateus** [sindresorhus/fast-cli#42]
Hello everyone!
I am using a virtual machine from google cloud and we know they have an amazing host.

In case, when doing the line commands:
fast —download and fast —upload I am getting this results:

![9AD4014B-6107-4929-AAB0-109FF21A3EC3](https://user-images.githubusercontent.com/50813027/72191602-7dd52400-33e1-11ea-828e-c403ec6e986d.jpeg)

I’d like to know better if fast.com cli commands are working fine on download/upload tests. 
Can we trust this results?!

Thanks! Hope to hear from you
:)

 >> Another very important point is: 
I can’t get this high values (down/up > 4.35gbps/4.43gbps) from fast.com website. I just get it when doing by line commands. What could it be? tks!!

**Comment by mpgmateus** [comment]
Another point is: I can’t get this high values (down/up > 4.35gbps/4.43gbps) from fast.com website. I just get it when doing line commands. What could it be? tks!!

**Comment by sindresorhus** [comment]
I answered this in an email.
