### ISSUE TITLE
Failed to launch chromium error when running command

### ISSUE THREAD

**Issue by lemsans** [sindresorhus/fast-cli#44]
I did everything the README.md file required me to install, after running it displayed this:

root@------:~# fast
Failed to launch chrome!
/usr/local/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

root@------:~# 

Keep in mind i tried to do this on multiple servers. Any ideas?

**Comment by tomsinclair94** [comment]
@lemsans I followed the steps (just 1 command actually) on [this site](https://techoverflow.net/2018/06/05/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-cannot-open-shared-object-file-no-such-file-or-directory/) to install some missing libraries and this fixed my issue and it runs fine now

**Comment by lemsans** [comment]
thank you, the command works great now
