### ISSUE TITLE
Fast.com cli not working... 0kbps output

### ISSUE THREAD

**Issue by mpgmateus** [sindresorhus/fast-cli#45]
Hello!! How are you?

Well... I’ve checked that its getting an error when trying to execute fast.com cli

I installed fast cli with the following command: snap install fast

When I try to execute fast —upload and then fast —download I always get 0 Kbps.

Please, check my screen:

![ADC606CC-3B76-4222-A46E-34524CDE8AB2](https://user-images.githubusercontent.com/50813027/77708944-4ae60980-6fa8-11ea-9bb7-9d8a65c127dc.png)

Do you have an idea on what could be happening!?

It used to work very nice!

Thank you very much!

Hope to hear from you

Sincerely,
Mat

**Comment by emanuelbernardes** [comment]
Don't use the snap install.
Run:
`sudo apt -y install node npm gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

npm install --global fast-cli
export PATH=$PATH:/usr/local/bin
`
And then
`fast -u`
