### ISSUE TITLE
error while compiling from source

### ISSUE THREAD

**Issue by UchihaSR** [sindresorhus/fast-cli#51]
node -v
v12.18.3

 i cloned this repo and did npm install to install all the dependencies  but it is failing to run due to some error, i am new to javascript and its framework.

> npm run test

> fast-cli@2.4.0 test C:\Users\Itachi-PC\Javascript_tutorial\fast-cli
> xo && ava

  1 test failed

  default

  C:\Users\Itachi-PC\Javascript_tutorial\fast-cli\test.js:6

   5: test.cb('default', t => {
   6:   const cp = childProcess.spawn('./cli.js', {stdio: 'inherit'});
   7:

  Error thrown in test:

  Error {
    code: 'UNKNOWN',
    errno: 'UNKNOWN',
    syscall: 'spawn',
    message: 'spawn UNKNOWN',
  }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fast-cli@2.4.0 test: `xo && ava`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fast-cli@2.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by sindresorhus** [comment]
This is not the place to ask for basic Node.js support, unfortunately. Try finding a Node.js chat/forum.
