### ISSUE TITLE
Provide distribution packages

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [sindresorhus/fast-cli#57]
It would be great to have distribution packages for e.g.

- [ ] Arch Linux (AUR)
- [ ] Debian / Ubuntu (deb / PPA)
- [ ] Fedora / Red Hat (rpm)

That would tremendously simplify the use.

**Comment by sindresorhus** [comment]
Sorry, I don't have any interest in providing this. The code is open source, so anyone else is free to do so though.
