### ISSUE TITLE
Improve the API

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/fast-cli#6]
Currently it's just a callback that gets called for every changed value. Would be nicer to use a promise with an event emitter on it. The promise should resolve when done and have the same result object as the progress.

```js
const api = require('./api');

api().on('progress', result => {
    console.log('progress');
}).then(result => {
    console.log('done');
});
```

Pull request appreciated :)

**Comment by SamVerschueren** [comment]
Or an observable :)

**Comment by kevva** [comment]
I've implemented it as an emitter. Do you want an Observable instead?

**Comment by sindresorhus** [comment]
@SamVerschueren Hmm, interesting! Didn't think of using Observables. How would it look like? Observables bring in a lot of instance methods, so would probably be weird to have a hybrid promise/observable.

**Comment by SamVerschueren** [comment]
Forgot about the issue a little bit :).

I believe this is a perfect use case for an observable to be honest.

```js
api().subscribe(
    value => {
        console.log(value),
    },
    err => {
        console.log(err.message);
    },
    () => {
        console.log('fast cli is done')
    }
);
```

**Comment by sindresorhus** [comment]
@SamVerschueren Agreed. Let's go with that.

Can use https://github.com/zenparsing/zen-observable

**Comment by kevva** [comment]
Alright, I'll update my PR then :).

**Comment by sindresorhus** [comment]
Anyone else wanna try their hand at this?
