### ISSUE TITLE
Protocol error: Target closed.

### ISSUE THREAD

**Issue by regul4rj0hn** [sindresorhus/fast-cli#69]
I'm on `Arch Linux 5.14.16`. Installed the tool and ran it with and without `sudo`:

```bash
~  % sudo fast -v                                                                                                           
› Protocol error (Page.navigate): Target closed.
```

Tried all the options to no avail. I don't see any verbose mode or logs that I can provide you with. Unfortunately time's a little tight for me right now to clone and troubleshoot, so maybe you have any quick suggestions.

Please let me know if there's anything else that I can do to help.

**Comment by sindresorhus** [comment]
Sounds like the underlying browser instance used in `fast-cli` crashed: https://stackoverflow.com/questions/51629151/puppeteer-protocol-error-page-navigate-target-closed

**Comment by regul4rj0hn** [comment]
Thanks, yeah I saw that issue. IDK why that would happen though I'm using Chromium latest as my main browser, works just fine.
