### ISSUE TITLE
"The term 'fast' is not recognized as the name of a cmdlet, function, script file, or operable  program."

### ISSUE THREAD

**Issue by AliceBunn** [sindresorhus/fast-cli#75]
I am on Windows 10 and I installed from npm. The output of `> npm ls` shows it is installed
> <name>@ C:\Users\<name>
`-- fast-cli@3.2.0'

but when I run `> fast` it outputs
> fast : The term 'fast' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and    
try again.
At line:1 char:1
>\+ fast
>\+ ~~~~
    + CategoryInfo          : ObjectNotFound: (fast:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sindresorhus** [comment]
This is not the place to get npm support.

https://github.community/c/software-development/47
