### ISSUE TITLE
Completely different results between fast-cli and fast.com

### ISSUE THREAD

**Issue by t0mcat1337** [sindresorhus/fast-cli#80]
Hi everyone,

I just tested fast-cli and wondering about the completely different results it produces at the same machine compared to fast.com website. I first ran fast-cli and right after that visited fast.com, these are the results

![grafik](https://user-images.githubusercontent.com/3826246/192583349-d42b9a1c-95a6-4fe1-9e47-7ac441fc6e12.png)

![grafik](https://user-images.githubusercontent.com/3826246/192583508-b561b9aa-42a0-493f-a3c2-f54d04df401f.png)

As you can see, fast-cli download results are 9 times slower, than fast.com, upload results are almost the same... 

Any idea?

**Comment by sindresorhus** [comment]
This project simply reads the results from Puppeteer, so there's not much I can do about this.
