### ISSUE TITLE
Is it possible to make this work in Android with Termux?

### ISSUE THREAD

**Issue by papb** [sindresorhus/fast-cli#82]
The readme says

> *This project uses Puppeteer under the hood. Most [install issues](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) are related to that.*

Indeed, I get `Error: Unsupported platform: android` from puppeteer's installation script when running `npm i -g fast-cli` on Termux on Android.

However, there is [this comment in a puppeteer issue](https://github.com/puppeteer/puppeteer/issues/9460#issuecomment-1370589669) which indicates that it might be possible to work around it, but it looks like it is some configuration that the code calling puppeteer would have to do.

Can this be done? Thanks

**Comment by sindresorhus** [comment]
PR welcome, but not something I plan to look into.
