### ISSUE TITLE
npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported

### ISSUE THREAD

**Issue by irbento** [sindresorhus/fast-cli#83]
Doesn't work anymore

npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported

changed 234 packages in 45s

37 packages are looking for funding
  run `npm fund` for details

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/fast-cli/releases/tag/v4.0.0
